# Generated by Django 4.0.5 on 2023-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_catagory_listing_delete_listig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='id',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='catagory',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
