# Generated by Django 4.0.5 on 2023-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_catagory_id_comments_item_listing_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='discription',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(),
        ),
    ]
