# Generated by Django 4.0.5 on 2023-02-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_bid_bids_listing_bids_user_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='discription',
            new_name='description',
        ),
    ]
