# Generated by Django 4.0.5 on 2023-03-05 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_catagory_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item', to='auctions.listing'),
        ),
    ]
