# Generated by Django 4.0.5 on 2023-03-05 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments_message_comments_user_listing_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
    ]
