# Generated by Django 4.0.5 on 2023-03-05 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 20, 49, 26, 396391)),
        ),
    ]
